Add missing <memory> include to fix win build
FAILED: obj/mojo/public/cpp/platform/platform/named_platform_channel_win.obj
../../mojo/public/cpp/platform/named_platform_channel_win.cc(58,8):  error: no member named 'unique_ptr' in namespace 'std'
  std::unique_ptr<void, decltype(::LocalFree)*> p(security_desc, ::LocalFree);
  ~~~~~^
../../mojo/public/cpp/platform/named_platform_channel_win.cc(58,23):  error: expected '(' for function-style cast or type construction
  std::unique_ptr<void, decltype(::LocalFree)*> p(security_desc, ::LocalFree);
                  ~~~~^
2 errors generated.