chromium_src: Add missing blink/public/mojom:mojom_platform dep
Fixes the following error:
  ../../content/public/browser/render_frame_host.h:18:10: fatal error:
    'third_party/blink/public/mojom/page/page_visibility_state.mojom.h'
    file not found
  #include "third_party/blink/public/mojom/page/page_visibility_state.mojom.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.