Linux does not use crashpad
A dependency on '//third_party/crashpad/crashpad:client' for all
platforms was causing this error on Linux:

  ../../third_party/crashpad/crashpad/util/net/http_transport_libcurl.cc:17:10:
  fatal error: 'curl/curl.h' file not found
  #include "curl/curl.h"
           ^~~~~~~~~~~~~

It is only needed on mac, because of
'//chrome/browser/google/google_update_settings_posix.cc'.