Rework UpgradeDetectorImpl in chromium_src/
Use the upstream version and add stubs for
chrome/browser/google/google_brand.cc. It fixes the following linking
error:

  error: allocating an object of abstract class type '(anonymous
  namespace)::UpgradeDetectorImpl'
  static auto* const instance = new UpgradeDetectorImpl();
                                    ^