Fix indirection requires pointer operand
../../electron/vendor/brightray/browser/devtools_embedder_message_dispatcher.cc:72:41:
error: indirection requires pointer operand ('const base::Value'
invalid)
    return it != list.end() && GetValue(**it, &head) &&
                                            ^~~~