Add missing mojo dependency to content/public/common/window_container_type.mojom.h
In file included from
  electron/brave/browser/component_updater/brave_component_updater_configurator.cc:19:
In file included from ../../chrome/browser/browser_process.h:20:
In file included from ../../chrome/browser/browser_process_platform_part.h:20:
In file included from ../../chrome/browser/browser_process_platform_part_base.h:11:
../../content/public/browser/content_browser_client.h:28:10:
fatal error: 'content/public/common/window_container_type.mojom.h' file not found