Add missing //components/proximity_auth/public/interfaces mojo dep
To prevent this error:
```
gen/chrome/browser/extensions/api/generated_api_registration.cc:26:
file included from ../../chrome/browser/extensions/api/screenlock_private/screenlock_private_api.h:13:
../../components/proximity_auth/screenlock_bridge.h:16:10:
fatal error: 'components/proximity_auth/public/interfaces/auth_type.mojom.h'
file not found
```